scd1_cdc_pipeline_snowflake_sql 

USE ROLE ACCOUNT_ADMIN;

USE WAREHOUSE COMPUTE_WH; 

CREATE OR REPLACE DATABASE SCD1_DB;

CREATE OR REPLACE STORAGE INTEGRATION SCD1_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::501000278160:role/scd1role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://dea-project-1-scd1-databucket/data/');

DESC INTEGRATION SCD1_INT;  

CREATE OR REPLACE STAGE SCD1_DB.PUBLIC.SCD1_STAGE
STORAGE_INTEGRATION = SCD1_INT
URL= 's3://dea-project-1-scd1-databucket/data/';

ls @SCD1_DB.PUBLIC.SCD1_STAGE;

---------------------------------------------setting up Snowpipe
USE ROLE ACCOUNTADMIN;
 
USE WAREHOUSE COMPUTE_WH;
 
USE SCHEMA SCD1_DB.PUBLIC;

-- creation of source table
CREATE OR REPLACE TABLE SCD1_DB.PUBLIC.CUSTOMER_SOURCE
(
CUSTOMERNAME STRING,
PHONE STRING,
ADDRESSLINE1 STRING,
ADDRESSLINE2 STRING,
CITY STRING,
STATE STRING,
POSTALCODE STRING,
COUNTRY STRING,
TERRITORY STRING,
CONTACTFIRSTNAME STRING,
CONTACTLASTNAME STRING
);

-- pipe is created here. auto ingested, using .csv files. 

CREATE OR REPLACE PIPE SCD1_DB.PUBLIC.SCD1PIPE
AUTO_INGEST = TRUE AS
COPY INTO SCD1_DB.PUBLIC.CUSTOMER_SOURCE
FROM
(
SELECT
$1 AS CUSTOMERNAME,
$2 AS PHONE,
$3 AS ADDRESSLINE1,
$4 AS ADDRESSLINE2,
$5 AS CITY,
$6 AS STATE,
$7 AS POSTALCODE,
$8 AS COUNTRY,
$9 AS TERRITORY,
$10 AS CONTACTFIRSTNAME,
$11 AS CONTACTLASTNAME
FROM @SCD1_DB.PUBLIC.SCD1_STAGE)
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY ='"');

-- check to make ensure no errors. 

SELECT SYSTEM$PIPE_STATUS('SCD1_DB.PUBLIC.SCD1PIPE');

---- ***copy notification channel destination to use in event notification in S3.
USE SCHEMA SCD1_DB.PUBLIC;
SHOW PIPES;

--- returned to S3 to create event notification. 
-- ****(sqs queue is chosen destination with link from event channel entered)***

-- setting up the Stream

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA SCD1_DB.PUBLIC;

CREATE OR REPLACE STREAM SCD1_DB.PUBLIC.CUSTOMER_STREAM
ON TABLE SCD1_DB.PUBLIC.CUSTOMER_SOURCE
APPEND_ONLY = TRUE;

SELECT * FROM SCD1_DB.PUBLIC.CUSTOMER_STREAM;

-- setting up our taget table 

CREATE OR REPLACE TABLE SCD1_DB.PUBLIC.CUSTOMER
(
CONTACTFIRSTNAME STRING,
CONTACTLASTNAME STRING,
CUSTOMERNAME STRING,
PHONE STRING,
ADDRESSLINE1 STRING,
ADDRESSLINE2 STRING,
CITY STRING,
STATE STRING,
POSTALCODE STRING,
COUNTRY STRING,
TERRITORY STRING,
INSERT_DTS TIMESTAMP(6),
UPDATE_DTS TIMESTAMP(6)
);

-- perform scd1 logic on target table. create stored procedure.
CREATE OR REPLACE PROCEDURE SCD1_DB.PUBLIC.CUSTOMER_SP()
RETURNS VARCHAR(50)
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
try {

//Create statement BEGIN, Begins a transaction in the current session

snowflake.execute({sqlText:`BEGIN TRANSACTION;`});

//load data from Customer Stream to a temp table

snowflake.execute({sqlText:`CREATE OR REPLACE TEMPORARY TABLE SCD1_DB.PUBLIC.CUSTOMER_TEMP
AS
SELECT
CONTACTFIRSTNAME,
CONTACTLASTNAME,
CUSTOMERNAME,
PHONE,
ADDRESSLINE1,
ADDRESSLINE2,
CITY,
STATE,
POSTALCODE,
COUNTRY,
TERRITORY,
CURRENT_TIMESTAMP(6) AS INSERT_DTS,
CURRENT_TIMESTAMP(6) AS UPDATE_DTS
FROM SCD1_DB.PUBLIC.CUSTOMER_STREAM;`});

//Perfom the required SCD1 logic on the Customer Target table based on the primary column

snowflake.execute({sqlText:`MERGE INTO SCD1_DB.PUBLIC.CUSTOMER TGT
USING SCD1_DB.PUBLIC.CUSTOMER_TEMP TMP
ON TGT.CONTACTFIRSTNAME = TMP.CONTACTFIRSTNAME
AND TGT.CONTACTLASTNAME = TMP.CONTACTLASTNAME
WHEN MATCHED THEN UPDATE SET
TGT.CUSTOMERNAME = TMP.CUSTOMERNAME,
TGT.PHONE = TMP.PHONE,
TGT.ADDRESSLINE1 = TMP.ADDRESSLINE1,
TGT.ADDRESSLINE2 = TMP.ADDRESSLINE2,
TGT.CITY = TMP.CITY,
TGT.STATE = TMP.STATE,
TGT.POSTALCODE = TMP.POSTALCODE,
TGT.COUNTRY = TMP.COUNTRY,
TGT.TERRITORY = TMP.TERRITORY,
TGT.UPDATE_DTS = TMP.UPDATE_DTS
WHEN NOT MATCHED THEN INSERT 
(
CONTACTFIRSTNAME,
CONTACTLASTNAME,
CUSTOMERNAME,
PHONE,
ADDRESSLINE1,
ADDRESSLINE2,
CITY,
STATE,
POSTALCODE,
COUNTRY,
TERRITORY,
INSERT_DTS,
UPDATE_DTS
)
VALUES
(
TMP.CONTACTFIRSTNAME,
TMP.CONTACTLASTNAME,
TMP.CUSTOMERNAME,
TMP.PHONE,
TMP.ADDRESSLINE1,
TMP.ADDRESSLINE2,
TMP.CITY,
TMP.STATE,
TMP.POSTALCODE,
TMP.COUNTRY,
TMP.TERRITORY,
TMP.INSERT_DTS,
TMP.UPDATE_DTS
);`});

//Create statement COMMIT, Commits an open transaction in the current session

snowflake.execute({sqlText:`COMMIT;`});

//Statement returned for info and debuging purposes

return "Store Procedure Executed Successfully";
}

catch (err)
{
    result = 'Error: ' + err;
    snowflake.execute({sqlText:`ROLLBACK;`});
    throw result;
}
$$;

-- create task. every 1 minute the task will execute the stored procedure. 

CREATE OR REPLACE TASK SCD1_DB.PUBLIC.CUSTOMER_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('SCD1_DB.PUBLIC.CUSTOMER_STREAM')
AS CALL SCD1_DB.PUBLIC.CUSTOMER_SP();

-- ******all tasks start in suspended mode, so, the following will resume it.  
ALTER TASK SCD1_DB.PUBLIC.CUSTOMER_TASK RESUME;

-- verify it
SHOW TASKS;

SELECT * FROM SCD1_DB.PUBLIC.CUSTOMER_SOURCE;
SELECT * FROM SCD1_DB.PUBLIC.CUSTOMER;
--see if stream has data
SELECT SYSTEM$STREAM_HAS_DATA('SCD1_DB.PUBLIC.CUSTOMER_STREAM');

--reinsert rows into stream || if you goof up. 
INSERT INTO SCD1_DB.PUBLIC.CUSTOMER_SOURCE
SELECT * FROM SCD1_DB.PUBLIC.CUSTOMER_SOURCE;

--doublecheck to see if they are there.
SELECT SYSTEM$STREAM_HAS_DATA('SCD1_DB.PUBLIC.CUSTOMER_STREAM');

--the phone number changes from 808 to 171.
SELECT * FROM SCD1_DB.PUBLIC.CUSTOMER
WHERE
CONTACTFIRSTNAME = 'Elizabeth'
AND
CONTACTLASTNAME ='Yu';

-- change in city from nyc to norflox
SELECT * FROM SCD1_DB.PUBLIC.CUSTOMER
WHERE
CONTACTFIRSTNAME = 'Kyung'
AND
CONTACTLASTNAME ='Benitez';

-- no result in first file. after customer change is loaded from anaconda to s3, snowflake ingests it and the task is changed after one minute and when refreshed and code executed... all the changes appear: scd logic executed. 
SELECT * FROM SCD1_DB.PUBLIC.CUSTOMER
WHERE
CONTACTFIRSTNAME = 'John'
AND
CONTACTLASTNAME = 'Wick';